# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication
from datetime import datetime
import ctypes
import time
import sys
sys.path.append("./")
from Methods.GetPrices import GetPrices
from Methods.Database import Database


class Ui_AddShopForItem(object):
    #UI setup
    def setupUi(self, AddShop):
        AddShop.setObjectName("AddItem")
        AddShop.resize(890, 580)

        self.centralwidget = QtWidgets.QWidget(AddShop)
        self.centralwidget.setObjectName("centralwidget")

        self.labelItem = QtWidgets.QLineEdit(self.centralwidget)
        self.labelItem.setGeometry(QtCore.QRect(220, 130, 71, 51))
        self.labelItem.setReadOnly(True)
        self.labelItem.setObjectName("labelItem")

        self.labelShop = QtWidgets.QLineEdit(self.centralwidget)
        self.labelShop.setGeometry(QtCore.QRect(220, 190, 71, 51))
        self.labelShop.setReadOnly(True)
        self.labelShop.setObjectName("labelShop")

        self.labelUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.labelUrl.setGeometry(QtCore.QRect(220, 250, 71, 51))
        self.labelUrl.setReadOnly(True)
        self.labelUrl.setObjectName("labelUrl")

        self.itemDropMenu = QtWidgets.QComboBox(self.centralwidget)
        self.itemDropMenu.setGeometry(QtCore.QRect(290, 130, 391, 51))
        self.itemDropMenu.setObjectName("itemDropMenu")

        self.shopDropMenu = QtWidgets.QComboBox(self.centralwidget)
        self.shopDropMenu.setGeometry(QtCore.QRect(290, 190, 391, 51))
        self.shopDropMenu.setObjectName("shopDropMenu")

        self.inputUrl = QtWidgets.QTextEdit(self.centralwidget)
        self.inputUrl.setGeometry(QtCore.QRect(290, 250, 391, 51))
        self.inputUrl.setObjectName("inputUrl")

        self.btnAddItem = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddItem.setGeometry(QtCore.QRect(370, 310, 311, 81))
        self.btnAddItem.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.btnAddItem.setObjectName("btnAddItem")

        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnBack.setGeometry(QtCore.QRect(220, 310, 141, 81))
        self.btnBack.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.btnBack.setObjectName("btnBack")

        AddShop.setCentralWidget(self.centralwidget)
        self.retranslateUi(AddShop)
        QtCore.QMetaObject.connectSlotsByName(AddShop)

        self.btnAddItem.clicked.connect(self.addShopForItem)
        self.btnBack.clicked.connect(AddShop.close)

        #Set items to itemDropMenu
        self.setItems()
        


    #Finding the items' names from the database
    def setItems(self):
        itemNameList = Database.getItemNames()
        self.itemDropMenu.clear()
        self.itemDropMenu.setPlaceholderText(" ")
        self.itemDropMenu.setCurrentIndex(-1)
        self.itemDropMenu.currentTextChanged.connect(self.setShops)

        correctItemList = []

        for item in itemNameList:
            if item[0] in correctItemList:
                pass
            else:
                correctItemList.append(item[0])


        for row in correctItemList:
            self.itemDropMenu.addItem(row)


    #Finding the shops from the database
    def setShops(self):
        object = Database
        QApplication.processEvents()
        
        allShops = object.findShops()
        self.shopDropMenu.clear()
        self.shopDropMenu.setPlaceholderText(" ")
        self.shopDropMenu.setCurrentIndex(-1)
        item = self.itemDropMenu.currentText()
        itemShops = Database.checkShops(item)

    
        for row in allShops:
            if (row in itemShops):
                pass
            else:
                self.shopDropMenu.addItem(row[0])

    #Clears the inputs and shows a message that the shop has been added
    def clearInputs(self):
        self.inputUrl.clear()
        self.itemDropMenu.setCurrentIndex(-1)
        self.shopDropMenu.clear()
        self.Mbox("!", "Shop added.", 0)

    #Method for the message boxes
    def Mbox(self, title, text, style):
            return ctypes.windll.user32.MessageBoxW(0, text, title, style)

    #Adding a shop for an item
    def addShopForItem(self):
            databaseObject = Database
            QApplication.processEvents()

            itemName = self.itemDropMenu.currentText()
            shop = self.shopDropMenu.currentText()
            URL = self.inputUrl.toPlainText()
            date = datetime.today().strftime('%Y-%m-%d')

            if shop == "Jimms":

                if not (URL.startswith("https://www.jimms.fi/")):
                        self.Mbox("Warning","INVALID URL!", 0)
                else:
                        time.sleep(0.5)
                        priceJimms = GetPrices.getJimmsPrice(URL)
                        priceJimms = ''.join(priceJimms.split())
                        databaseObject.addItem(databaseObject, itemName, URL, shop)
                        databaseObject.addItemPrice(databaseObject, priceJimms, date, itemName, shop)
                        self.clearInputs()

            elif shop == "Verkkokauppa.com": 

                if not (URL.startswith("https://www.verkkokauppa.com/")):
                        self.Mbox("Warning", "INVALID URL!",0)
                else:
                        time.sleep(0.5)
                        priceVerkkokauppacom = GetPrices.getVerkkokauppaComPrice(URL)
                        priceVerkkokauppacom = ''.join(priceVerkkokauppacom.split())
                        databaseObject.addItem(databaseObject, itemName, URL, shop)
                        databaseObject.addItemPrice(databaseObject, priceVerkkokauppacom, date, itemName, shop)
                        self.clearInputs()

            elif shop == "Prisma": 

                if not (URL.startswith("https://www.prisma.fi/")):
                        self.Mbox("Warning", "INVALID URL!",0)
                else:
                        time.sleep(0.5)
                        pricePrisma = GetPrices.getPrismaPrice(URL)
                        pricePrisma = ''.join(pricePrisma.split())
                        databaseObject.addItem(databaseObject, itemName, URL, shop)
                        databaseObject.addItemPrice(databaseObject, pricePrisma, date, itemName, shop)
                        self.clearInputs()

            elif shop == "Karkkainen": 

                if not (URL.startswith("https://www.karkkainen.com/")):
                        self.Mbox("Warning", "INVALID URL!",0)
                else:
                        time.sleep(0.5)
                        priceKarkkainen = GetPrices.getKarkkainenPrice(URL)
                        priceKarkkainen = ''.join(priceKarkkainen.split())
                        databaseObject.addItem(databaseObject, itemName, URL, shop)
                        databaseObject.addItemPrice(databaseObject, priceKarkkainen, date, itemName, shop)
                        self.clearInputs()







    def retranslateUi(self, AddItem):
        _translate = QtCore.QCoreApplication.translate
        AddItem.setWindowTitle(_translate("AddItem", "MainWindow"))
        self.btnAddItem.setText(_translate("AddItem", "Add item"))
        self.inputUrl.setHtml(_translate("AddItem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
            "p, li { white-space: pre-wrap; }\n"
            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>"))
        self.labelUrl.setText(_translate("AddItem", "Url:"))
        self.labelShop.setText(_translate("AddItem", "Select shop:"))
        self.btnBack.setText(_translate("AddItem", "Back"))
        self.labelItem.setText(_translate("AddItem", "Select item:"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddShopForItem = QtWidgets.QMainWindow()
    ui = Ui_AddShopForItem()
    ui.setupUi(AddShopForItem)
    AddShopForItem.show()
    sys.exit(app.exec_())
